### PR TITLE
Faster installer and XF2 compatibility fixes

### PR DESCRIPTION
**Pull request by aakifn**
- Compatibility fixes to support xenforo.com/community running xenforo 2
- Speed up add-on install time by only rebuilding touched templates and permissions

This release has been tested by Xon and myself for a few weeks on an assortment of large boards with smooth operation and less time to go make a coffee or two been add-on upgrades.

### CODE REVIEW

**Review by chrisdeeming — COMMENTED** [review]
Somewhat busy, but quick scan through it all looks good to me. I'll let @Xon give the final approval.

**Comment by Xon** [comment]
@chrisdeeming LGTM, just putting up the release for this now. I've been running the 'faster install' parts for a while now. Been working well. Saves me so much time, great to see it is native to XF2.

**Comment by Xon** [comment]
@chrisdeeming @NixFifty just testing the add-on check and something isn't working. so hold off releasing it until I flip it to published.

**Comment by aakifn** [comment]
Forgot to fix up the update checker, sorted here: https://github.com/Xon/XenForo-AddOnInstaller/commit/71b2e3fc5135c953b851f0612a4343c2479564f7

**Comment by Xon** [comment]
@NixFifty yup looks fixed for me :)

@chrisdeeming if you can push this on xenforo.com at some stage that would be great !

**Pull request merged**
